### ISSUE TITLE
file not found

### ISSUE THREAD

**Issue by ljkfd3** [prometheusXN/LADAN#4]
![image](https://user-images.githubusercontent.com/42198090/83524995-f6ff2000-a516-11ea-84be-88fd47cd9f55.png)

**Comment by prometheusXN** [comment]
This is a word embedding file. It's too large to upload. You can generate the file as described in our paper

**Comment by ljkfd3** [comment]
I am a newcomer. In order to ensure the consistency of the experimental results, could you give me the code that generate word embedding ?

**Comment by prometheusXN** [comment]
Please give me your email. I'll send it to you by @qq.com later.



xunuo0109@hotmail.com
 
From: warren
Date: 2020-06-02 22:26
To: prometheusXN/LADAN
CC: prometheusXN; Comment
Subject: Re: [prometheusXN/LADAN] file not found (#4)
I am a newcomer. In order to ensure the consistency of the experimental results, could you give me the code that generate word embedding ?

**Comment by ljkfd3** [comment]
Thanks a lot. This is my mail box schec@foxmail.com.

**Comment by ljkfd3** [comment]
Thanks a lot. This is my mail box schec@foxmail.com.

**Comment by ljkfd3** [comment]
2020-06-04 17:21:55.586537: W tensorflow/core/framework/op_kernel.cc:1401] OP_REQUIRES failed at variable_ops.cc:104 : Already exists: Resource __per_step_3/gradients/fact_re_encoder/sequential_3/bidirectional_3/while/ReadVariableOp/Enter_grad/ArithmeticOptimizer/AddOpsRewrite_Add/tmp_var/N10tensorflow19TemporaryVariableOp6TmpVarE
2020-06-04 17:21:55.590057: W tensorflow/core/framework/op_kernel.cc:1401] OP_REQUIRES failed at variable_ops.cc:104 : Already exists: Resource __per_step_3/gradients/fact_re_encoder/sequential_3/bidirectional_3/while/ReadVariableOp/Enter_grad/ArithmeticOptimizer/AddOpsRewrite_Add/tmp_var/N10tensorflow19TemporaryVariableOp6TmpVarE
2020-06-04 17:21:55.592007: W tensorflow/core/framework/op_kernel.cc:1401] OP_REQUIRES failed at variable_ops.cc:104 : Already exists: Resource __per_step_3/gradients/fact_re_encoder/sequential_3/bidirectional_3/while/ReadVariableOp/Enter_grad/ArithmeticOptimizer/AddOpsRewrite_Add/tmp_var/N10tensorflow19TemporaryVariableOp6TmpVarE
2020-06-04 17:21:55.593037: W tensorflow/core/framework/op_kernel.cc:1401] OP_REQUIRES failed at variable_ops.cc:104 : Already exists: Resource __per_step_3/gradients/fact_re_encoder/sequential_3/bidirectional_3/while/ReadVariableOp/Enter_grad/ArithmeticOptimizer/AddOpsRewrite_Add/tmp_var/N10tensorflow19TemporaryVariableOp6TmpVarE
2020-06-04 17:21:55.594465: W tensorflow/core/framework/op_kernel.cc:1401] OP_REQUIRES failed at variable_ops.cc:104 : Already exists: Resource __per_step_3/gradients/fact_re_encoder/sequential_3/bidirectional_3/while/ReadVariableOp/Enter_grad/ArithmeticOptimizer/AddOpsRewrite_Add/tmp_var/N10tensorflow19TemporaryVariableOp6TmpVarE
2020-06-04 17:21:55.596972: W tensorflow/core/framework/op_kernel.cc:1401] OP_REQUIRES failed at variable_ops.cc:104 : Already exists: Resource __per_step_3/gradients/fact_re_encoder/sequential_3/bidirectional_3/while/ReadVariableOp/Enter_grad/ArithmeticOptimizer/AddOpsRewrite_Add/tmp_var/N10tensorflow19TemporaryVariableOp6TmpVarE
2020-06-04 17:21:55.604578: W tensorflow/core/framework/op_kernel.cc:1401] OP_REQUIRES failed at variable_ops.cc:104 : Already exists: Resource __per_step_3/gradients/fact_re_encoder/sequential_3/bidirectional_3/while/ReadVariableOp/Enter_grad/ArithmeticOptimizer/AddOpsRewrite_Add/tmp_var/N10tensorflow19TemporaryVariableOp6TmpVarE
2020-06-04 17:21:55.611074: W tensorflow/core/framework/op_kernel.cc:1401] OP_REQUIRES failed at variable_ops.cc:104 : Already exists: Resource __per_step_3/gradients/fact_re_encoder/sequential_3/bidirectional_3/while/ReadVariableOp/Enter_grad/ArithmeticOptimizer/AddOpsRewrite_Add/tmp_var/N10tensorflow19TemporaryVariableOp6TmpVarE
2020-06-04 17:21:55.612975: W tensorflow/core/framework/op_kernel.cc:1401] OP_REQUIRES failed at variable_ops.cc:104 : Already exists: Resource __per_step_3/gradients/fact_re_encoder/sequential_3/bidirectional_3/while/ReadVariableOp/Enter_grad/ArithmeticOptimizer/AddOpsRewrite_Add/tmp_var/N10tensorflow19TemporaryVariableOp6TmpVarE
2020-06-04 17:21:55.615330: W tensorflow/core/framework/op_kernel.cc:1401] OP_REQUIRES failed at variable_ops.cc:104 : Already exists: Resource __per_step_3/gradients/fact_re_encoder/sequential_3/bidirectional_3/while/ReadVariableOp/Enter_grad/ArithmeticOptimizer/AddOpsRewrite_Add/tmp_var/N10tensorflow19TemporaryVariableOp6TmpVarE
2020-06-04 17:21:55.624990: W tensorflow/core/framework/op_kernel.cc:1401] OP_REQUIRES failed at variable_ops.cc:104 : Already exists: Resource __per_step_3/gradients/fact_re_encoder/sequential_3/bidirectional_3/while/ReadVariableOp/Enter_grad/ArithmeticOptimizer/AddOpsRewrite_Add/tmp_var/N10tensorflow19TemporaryVariableOp6TmpVarE
2020-06-04 17:21:55.659802: W tensorflow/core/framework/op_kernel.cc:1401] OP_REQUIRES failed at variable_ops.cc:104 : Already exists: Resource __per_step_3/gradients/fact_re_encoder/sequential_3/bidirectional_3/while/ReadVariableOp/Enter_grad/ArithmeticOptimizer/AddOpsRewrite_Add/tmp_var/N10tensorflow19TemporaryVariableOp6TmpVarE
Traceback (most recent call last):
  File "/home/wentingcan/anaconda3/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1334, in _do_call
    return fn(*args)
  File "/home/wentingcan/anaconda3/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1319, in _run_fn
    options, feed_dict, fetch_list, target_list, run_metadata)
  File "/home/wentingcan/anaconda3/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1407, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.AlreadyExistsError: Resource __per_step_3/gradients/fact_re_encoder/sequential_3/bidirectional_3/while/ReadVariableOp/Enter_grad/ArithmeticOptimizer/AddOpsRewrite_Add/tmp_var/N10tensorflow19TemporaryVariableOp6TmpVarE
	 [[{{node gradients/fact_re_encoder/sequential_3/bidirectional_3/while/ReadVariableOp/Enter_grad/ArithmeticOptimizer/AddOpsRewrite_Add/tmp_var}}]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "LADAN+Topjudge_small.py", line 505, in <module>
    loss_value, _, graph_chose_value= sess.run([loss_total, train_op, graph_chose_loss], feed_dict=feed_dict)
  File "/home/wentingcan/anaconda3/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 929, in run
    run_metadata_ptr)
  File "/home/wentingcan/anaconda3/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1152, in _run
    feed_dict_tensor, options, run_metadata)
  File "/home/wentingcan/anaconda3/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1328, in _do_run
    run_metadata)
  File "/home/wentingcan/anaconda3/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1348, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.AlreadyExistsError: Resource __per_step_3/gradients/fact_re_encoder/sequential_3/bidirectional_3/while/ReadVariableOp/Enter_grad/ArithmeticOptimizer/AddOpsRewrite_Add/tmp_var/N10tensorflow19TemporaryVariableOp6TmpVarE
	 [[{{node gradients/fact_re_encoder/sequential_3/bidirectional_3/while/ReadVariableOp/Enter_grad/ArithmeticOptimizer/AddOpsRewrite_Add/tmp_var}}]]

when I run LADAN+Topjudge_small.py , the above error occur。

**Comment by ljkfd3** [comment]
This error may be a problem with the version

**Comment by ljkfd3** [comment]
What is your tensorflow and keras version?

**Comment by SkyErnest** [comment]
@ljkfd3 Hello, I am one of the authors. Our Tensorflow version is 1.14 and Keras version is 2.3.1. This error may occur when you use Tensorflow and keras simultaneously. So I suggest to use keras by "from tensorflow import keras" in all the scripts.

**Comment by SkyErnest** [comment]
By the way, it's not necessary to install the package keras because it's contained in tensorflow

**Comment by ljkfd3** [comment]
I tried  "from tensorflow import keras", but it is still error. Finally I solve this problem by installing the corresponding version of keras.
![image](https://user-images.githubusercontent.com/42198090/83931664-8c790900-a7d0-11ea-851d-573d60538fe4.png)

**Comment by ljkfd3** [comment]
After I solve the problem of version above , new error occur 。。。

Traceback (most recent call last):
  File "LADAN+Topjudge_small.py", line 274, in <module>
    rep_law = run_model(law_description, law_mask, model)
  File "LADAN+Topjudge_small.py", line 150, in run_model
    out = model(input, mask=mask)
  File "/home/wentingcan/my_program/anaconda3/lib/python3.6/site-packages/keras/engine/base_layer.py", line 451, in __call__
    output = self.call(inputs, **kwargs)
  File "/home/wentingcan/my_program/anaconda3/lib/python3.6/site-packages/keras/engine/network.py", line 570, in call
    output_tensors, _, _ = self.run_internal_graph(inputs, masks)
  File "/home/wentingcan/my_program/anaconda3/lib/python3.6/site-packages/keras/engine/network.py", line 727, in run_internal_graph
    layer.call(computed_tensor, **kwargs))
  File "/home/wentingcan/my_program/anaconda3/lib/python3.6/site-packages/keras/layers/wrappers.py", line 521, in call
    initial_state=forward_state, **kwargs)
  File "/home/wentingcan/my_program/anaconda3/lib/python3.6/site-packages/keras/layers/recurrent.py", line 1683, in call
    initial_state=initial_state)
  File "/home/wentingcan/my_program/anaconda3/lib/python3.6/site-packages/keras/layers/recurrent.py", line 674, in call
    input_length=timesteps)
  File "/home/wentingcan/my_program/anaconda3/lib/python3.6/site-packages/keras/backend/tensorflow_backend.py", line 3109, in rnn
    'got {}'.format(mask.shape))
ValueError: mask should have `shape=(samples, time)`, got (1545, 100, 1)

**Comment by xjtusedy** [comment]
Would you like to give me a copy of this word embedding file or the code can generate this? My email box is dingyi6698@qq.com. Thanks a lot!

**Comment by qq594495953** [comment]
Would you like to give me a copy of this word embedding file or the code can generate this? My email box is 617314027@qq.com. Thanks a lot!

**Comment by lvyougang** [comment]
Would you like to give me a copy of this word embedding file or the code can generate this? My email box is 1071128051@qq.com. Thanks a lot!

**Comment by KennardXiong** [comment]
I would appreciate it very much if you could send me a copy of the word  embedding file. My email box is xionghantao94@163.com. Thanks a lot.

**Comment by prometheusXN** [comment]
Now, you can download the word embedding file! Please read the README.md

**Comment by winnerLuo** [comment]
> After I solve the problem of version above , new error occur 。。。
> 
> Traceback (most recent call last): File "LADAN+Topjudge_small.py", line 274, in rep_law = run_model(law_description, law_mask, model) File "LADAN+Topjudge_small.py", line 150, in run_model out = model(input, mask=mask) File "/home/wentingcan/my_program/anaconda3/lib/python3.6/site-packages/keras/engine/base_layer.py", line 451, in **call** output = self.call(inputs, **kwargs) File "/home/wentingcan/my_program/anaconda3/lib/python3.6/site-packages/keras/engine/network.py", line 570, in call output_tensors, _, _ = self.run_internal_graph(inputs, masks) File "/home/wentingcan/my_program/anaconda3/lib/python3.6/site-packages/keras/engine/network.py", line 727, in run_internal_graph layer.call(computed_tensor, **kwargs)) File "/home/wentingcan/my_program/anaconda3/lib/python3.6/site-packages/keras/layers/wrappers.py", line 521, in call initial_state=forward_state, **kwargs) File "/home/wentingcan/my_program/anaconda3/lib/python3.6/site-packages/keras/layers/recurrent.py", line 1683, in call initial_state=initial_state) File "/home/wentingcan/my_program/anaconda3/lib/python3.6/site-packages/keras/layers/recurrent.py", line 674, in call input_length=timesteps) File "/home/wentingcan/my_program/anaconda3/lib/python3.6/site-packages/keras/backend/tensorflow_backend.py", line 3109, in rnn 'got {}'.format(mask.shape)) ValueError: mask should have `shape=(samples, time)`, got (1545, 100, 1)

now， can you run the model ?
i need your successful enviornment

**Comment by winnerLuo** [comment]
> After I solve the problem of version above , new error occur 。。。
> 
> Traceback (most recent call last): File "LADAN+Topjudge_small.py", line 274, in rep_law = run_model(law_description, law_mask, model) File "LADAN+Topjudge_small.py", line 150, in run_model out = model(input, mask=mask) File "/home/wentingcan/my_program/anaconda3/lib/python3.6/site-packages/keras/engine/base_layer.py", line 451, in **call** output = self.call(inputs, **kwargs) File "/home/wentingcan/my_program/anaconda3/lib/python3.6/site-packages/keras/engine/network.py", line 570, in call output_tensors, _, _ = self.run_internal_graph(inputs, masks) File "/home/wentingcan/my_program/anaconda3/lib/python3.6/site-packages/keras/engine/network.py", line 727, in run_internal_graph layer.call(computed_tensor, **kwargs)) File "/home/wentingcan/my_program/anaconda3/lib/python3.6/site-packages/keras/layers/wrappers.py", line 521, in call initial_state=forward_state, **kwargs) File "/home/wentingcan/my_program/anaconda3/lib/python3.6/site-packages/keras/layers/recurrent.py", line 1683, in call initial_state=initial_state) File "/home/wentingcan/my_program/anaconda3/lib/python3.6/site-packages/keras/layers/recurrent.py", line 674, in call input_length=timesteps) File "/home/wentingcan/my_program/anaconda3/lib/python3.6/site-packages/keras/backend/tensorflow_backend.py", line 3109, in rnn 'got {}'.format(mask.shape)) ValueError: mask should have `shape=(samples, time)`, got (1545, 100, 1)

你好，你成功运行出来了吗
